Add DNS lookup check step back to cloudbuild.yaml
Reintroduced DNS check step using Alpine image.

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,18 +1,5 @@
 steps:
-   - name: 'alpine'
-     entrypoint: 'sh'
-     args: 
-      - '-c'
-      - |
-        apk add --no-cache bind-tools
-        if dig +short github.com | grep -E '^[0-9.]+$' > /dev/null; then
-          echo "DNS lookup successful"
-        else
-          echo "DNS lookup failed for domain.com"
-          exit 1
-        fi
-    
-  # Build the application using Maven
+   # Build the application using Maven
   - name: 'maven'
     entrypoint: 'mvn'
     args: ['clean', 'install', '-DskipTests']
@@ -47,6 +34,20 @@ steps:
       - '$_DEPLOY_REGION'
       - '--platform'
       - 'managed'
+      
+  - name: 'alpine'
+     entrypoint: 'sh'
+     args: 
+      - '-c'
+      - |
+        apk add --no-cache bind-tools
+        if dig +short github.com | grep -E '^[0-9.]+$' > /dev/null; then
+          echo "DNS lookup successful"
+        else
+          echo "DNS lookup failed for domain.com"
+          exit 1
+        fi
+     id: 'dns-check'
 logsBucket: 'gs://logs-bucket-demo'
 options:
   logging: GCS_ONLY
