Enhance DNS check with IP output

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,17 +1,18 @@
 steps:   
-  - name: 'alpine'
-    entrypoint: 'sh'
-    args:
-      - '-c'
-      - |
-        apk add --no-cache bind-tools
-        if dig +short github.com | grep -E '^[0-9.]+$' > /dev/null; then
-          echo "DNS lookup successful"
-        else
-          echo "DNS lookup failed for domain.com"
-          exit 1
-        fi
-    id: 'dns-check'
+ - name: 'alpine'
+  entrypoint: 'sh'
+  args:
+    - '-c'
+    - |
+      apk add --no-cache bind-tools
+      IP=$(dig +short github.com | grep -E '^[0-9.]+$')
+      if [ -n "$IP" ]; then
+        echo "DNS lookup successful, IP: $IP"
+      else
+        echo "DNS lookup failed for github.com"
+        exit 1
+      fi
+  id: 'dns-check'
 logsBucket: 'gs://logs-bucket-demo'
 options:
   logging: GCS_ONLY
